FROM ghcr.io/astral-sh/uv:0.6-python3.11-bookworm-slim

WORKDIR /mlflow

RUN uv pip install --system mlflow==2.18.0 psutil

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./artifacts"]
