apiVersion: v1
kind: Secret
metadata:
  name: {{ include "churn-radar.fullname" . }}-secret
  labels:
    {{- include "churn-radar.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
